name: Convert Activities to JSON
on:
  push:
    paths:
      - 'activities.md'
  # allows to manually run the job at any time
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node ./convert.js